# Generated by Django 4.2 on 2023-04-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
        ("leavemanagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaveapplication",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_applications",
                to="students.student",
            ),
        ),
    ]
