# Generated by Django 4.2 on 2023-04-26 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wardens", "0001_initial"),
        ("leavemanagement", "0002_alter_leaveapplication_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveapplication",
            name="leave_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leave_applications",
                to="wardens.warden",
            ),
        ),
    ]
